.TH netactview 1 "June 2014" "GTK Applications" ""
.SH NAME
netactview \- graphical network connections viewer

.SH SYNOPSIS
.B netactview 

.SH DESCRIPTION
.LP 
With \fInetactview\fP you can view the current network connections using a 
graphical interface.
.LP
The shown network connections information is similar with the output of 
the standard command line tool netstat when used for network connections:
.RS
netstat -patu
.RE
.RS
netstat -patun
.RE
.LP
netactview documentation is online using the wiki format:
.RS 0
http://netactview.sourceforge.net/wiki/
.RE


.SH AUTHORS
.LP
Written by Mihai Varzaru <mihaiv@gmail.com>.
.LP 

.SH SEE ALSO
netstat(8)

